### PR TITLE
`promiseRaceWithSignal` - Fix leak

### LINKED ISSUE #17: Memory Leak in promiseRaceWithSignal
- See https://github.com/pixiebrix/pixiebrix-source/pull/2607
- It looks like the underlying promiseFromSignal has some potential memory leak bugs: https://github.com/fregante/abort-utils/blob/main/source/promise-from-signal.ts
  - The abort check doesn't have `once: true`: https://github.com/fregante/abort-utils/blob/main/source/promise-from-signal.ts#L28
  - If the main promise wins the race, how is the promise from the signal cleaned up?

### PR DESCRIPTION
**Pull request by fregante**
- Should fix #17 

The implementation is slightly longer than `wrapAbort` because it has an extra option (`rejectOnAbort: false`) and it accepts `AbortController` 

cc @twschiller

### CODE REVIEW

File: source/promise-race-with-signal.ts [hunk 1]
```diff
@@ -8,19 +8,36 @@ import {promiseFromSignal} from './promise-from-signal.js';
...
-async function promiseRaceWithSignal<T, AbortRejects extends boolean = true>(
+export async function promiseRaceWithSignal<T, AbortRejects extends boolean = true, ReturnValue = AbortRejects extends false ? T | unknown : T>(
 	promise: Promise<T>,
 	signal: AbortSignal | AbortController | undefined,
 	{abortRejects = true as AbortRejects}: {abortRejects?: AbortRejects} = {},
-): Promise<AbortRejects extends false ? T | unknown : T> {
+): Promise<ReturnValue> {
 	if (!signal) {
-		return promise;
+		return promise as ReturnValue;
```
Comment (twschiller) [inline source/promise-race-with-signal.ts]: I think this needs to be `as Promise<ReturnValue>`?

**Comment by fregante** [comment]
I cleaned up the function to remove all assertions.

As for your questions, already tried, but TS pulled out the usual `'ReturnValue' is assignable to the constraint of type 'T', but 'T' could be instantiated with a different subtype of constraint 'ReturnValue'.` 🤷‍♂️

File: source/promise-race-with-signal.ts [hunk 2]
```diff
@@ -8,19 +8,48 @@ import {promiseFromSignal} from './promise-from-signal.js';
...
+		const handleAbort = () => {
+			if (abortRejects) {
+				reject(trueSignal.reason);
+			} else {
+				resolve(trueSignal.reason);
+			}
+		};
+
+		trueSignal.addEventListener('abort', handleAbort, {once: true});
+		promise.then(resolve, reject).finally(() => {
```
Comment (twschiller) [inline source/promise-race-with-signal.ts:49]: Wouldn't this cause an uncaught error if the signal aborted first because it will call resolve/reject a 2nd time?

Comment (fregante) [reply source/promise-race-with-signal.ts:49]: Promises can only be fulfilled once, so successive resolve/reject calls are noops

Screenshot
